version: "2"
services:
    app:
        build: ./app
        environment:
            MYSQL_USER: root #changeme
            MYSQL_PASSWORD: root #changeme
            MYSQL_HOST: db
            MYSQL_DB: colors
            MYSQL_PORT: 3306

        links:
            - db
        ports:
            - "5000:5000"
    db:
        image: mysql:8.0
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root #changeme
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro